# Generated by Django 3.0.4 on 2020-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivers',
            name='Delivery_status',
            field=models.CharField(choices=[('1', 'DELIVERED'), ('2', 'NOT DELIVERED')], max_length=50, verbose_name='Delivery Status'),
        ),
    ]
