# Generated by Django 3.0.4 on 2020-03-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0002_auto_20200330_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delivers',
            unique_together={('Invoice_no', 'Transport_id')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase_consists_of',
            unique_together={('Purchase_id', 'Prod_code')},
        ),
        migrations.AlterUniqueTogether(
            name='sale_consists_of',
            unique_together={('Invoice_no', 'Prod_code')},
        ),
    ]
