# Generated by Django 3.0.4 on 2020-04-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0003_auto_20200331_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact'),
        ),
    ]
