# Generated by Django 3.0.4 on 2020-04-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0004_auto_20200401_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterModelTable(
            name='office_expense',
            table='Office_Expense',
        ),
    ]
