# Generated by Django 3.0.4 on 2020-04-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0006_auto_20200405_1746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='office_expense',
            table='Office_Expense',
        ),
    ]
