# Generated by Django 3.0.4 on 2020-04-14 13:10

from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0007_auto_20200405_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(validators=[paint.validators.nonneg], verbose_name='Salary'),
        ),
    ]
