# Generated by Django 3.0.4 on 2020-04-14 13:17

import django.core.validators
from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0008_auto_20200414_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Contact',
            field=models.IntegerField(blank=True, null=True, validators=[paint.validators.nonneg], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='Contact_no',
            field=models.BigIntegerField(blank=True, null=True, validators=[paint.validators.nonneg], verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Bank_Accno',
            field=models.BigIntegerField(validators=[paint.validators.nonneg], verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone_no',
            field=models.BigIntegerField(validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MaxValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='office_expense',
            name='Amount',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Rate',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Shelf_life',
            field=models.IntegerField(blank=True, null=True, validators=[paint.validators.nonneg], verbose_name='Shelf Life'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Stock_level',
            field=models.IntegerField(validators=[paint.validators.nonneg], verbose_name='Stock Level'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Discount_in_percentage',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Discount(in percent)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Tax_in_percentage',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Tax(in percent)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Total_amount',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Discount_in_percentage',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Discount(in percent)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Tax_in_percentage',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Tax(in percent)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Total_amount',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='Contact',
            field=models.BigIntegerField(validators=[paint.validators.nonneg], verbose_name='Contact No'),
        ),
    ]
