# Generated by Django 3.0.4 on 2020-04-14 13:18

import django.core.validators
from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0009_auto_20200414_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone_no',
            field=models.BigIntegerField(validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='Phone No'),
        ),
    ]
