# Generated by Django 3.0.4 on 2020-04-14 13:28

import django.core.validators
from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0010_auto_20200414_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Contact',
            field=models.IntegerField(blank=True, null=True, validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Customer_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Name')], verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='Contact_no',
            field=models.BigIntegerField(blank=True, null=True, validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='Distributor_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Name')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_firstname',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Name')], verbose_name='Employee First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_lastname',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Name')], verbose_name='Employee Last Name'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='Contact',
            field=models.BigIntegerField(validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='Transport_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Name')], verbose_name='Transport Name'),
        ),
    ]
