# Generated by Django 3.0.4 on 2020-04-14 13:51

import django.core.validators
from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0012_auto_20200414_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivers',
            name='Date',
            field=models.DateField(validators=[paint.validators.datevalid], verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='office_expense',
            name='Expenditure_date',
            field=models.DateField(validators=[paint.validators.datevalid], verbose_name='Expenditure Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Date_of_Purchase',
            field=models.DateField(validators=[paint.validators.datevalid], verbose_name='Date Of Puchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Discount_in_percentage',
            field=models.FloatField(validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(100, 'Discount can not be more than 100%%')], verbose_name='Discount(in percent)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Date_of_order',
            field=models.DateField(validators=[paint.validators.datevalid], verbose_name='Date Of Order'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Discount_in_percentage',
            field=models.FloatField(validators=[paint.validators.nonneg, django.core.validators.MaxValueValidator(100, 'Discount can not be more than 100%%')], verbose_name='Discount(in percent)'),
        ),
    ]
