# Generated by Django 3.0.4 on 2020-04-14 15:02

from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0013_auto_20200414_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Rate',
            field=models.FloatField(validators=[paint.validators.nonneg], verbose_name='Rate(per unit)'),
        ),
    ]
