# Generated by Django 3.0.5 on 2020-04-24 17:40

from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0015_auto_20200424_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[paint.validators.nonneg], verbose_name='Total Amount'),
        ),
    ]
