# Generated by Django 3.0.5 on 2020-04-25 17:45

from django.db import migrations, models
import paint.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0020_auto_20200425_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[paint.validators.nonneg], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Total_amount',
            field=models.FloatField(blank=True, null=True, validators=[paint.validators.nonneg], verbose_name='Total Amount'),
        ),
    ]
