# Generated by Django 3.0.5 on 2020-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0021_auto_20200425_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_consists_of',
            name='Quantity',
            field=models.IntegerField(max_length=20, verbose_name='Quantity'),
        ),
    ]
