# Generated by Django 3.0.5 on 2020-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0024_auto_20200425_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_expense',
            name='Mode_of_payment',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CHEQUE', 'CHEQUE'), ('CASH', 'CASH'), ('CARD', 'CARD')], max_length=50, verbose_name='Mode Of Payment'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Mode_of_Payment',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CHEQUE', 'CHEQUE'), ('CASH', 'CASH'), ('CARD', 'CARD')], max_length=50, verbose_name='Mode Of Payment'),
        ),
    ]
